version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=travedi@123
      - MYSQL_PASSWORD=travedi@123
      - MYSQL_DATABASE=demo
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/spring_crud?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "travedi@123"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-docker



