server:
  port: 8083
  servlet:
    context-path: /demo


spring:
  datasource:
    url: jdbc:mysql://mysql-docker:3306/spring_crud?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: travedi@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update